---
- name: install homebrew dependencies
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - build-essential
    - procps
    - curl
    - file
    - git

- name: install homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" NONINTERACTIVE=1

- name: add homebrew to path
  shell: |
    echo '# Set PATH, MANPATH, etc., for Homebrew.' >> $HOME/.profile
    echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $HOME/.profile

- name: eval homebrew
  shell: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

- name: restart shell
  shell: . $HOME/.profile

- name: install node
  shell: brew install nvm

- name: add nvm to .bashrc
  shell: |
    echo 'export NVM_DIR="$HOME/.nvm"' >> $HOME/.bashrc
    echo '[ -s "/home/linuxbrew/.linuxbrew/opt/nvm/nvm.sh" ] && \. "/home/linuxbrew/.linuxbrew/opt/nvm/nvm.sh"'  >> $HOME/.bashrc
    echo '[ -s "/home/linuxbrew/.linuxbrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/home/linuxbrew/.linuxbrew/opt/nvm/etc/bash_completion.d/nvm"' >> $HOME/.bashrc

- name: restart shell
  shell: . $HOME/.bashrc

- name: git clone .dotfiles
  ansible.builtin.git:
    repo: https://github.com/Delta-a-Sierra/.dotfile
    dest: $HOME/.dotfiles
    single_branch: yes
    version: tidy
